var MissionType = {
    MISSION1: { image: '1.jpg', descKey: 'transport' },
    MISSION2: { image: '2.jpg', descKey: 'transport' },
    MISSION3: { image: '3.jpg', descKey: 'transport' },
    MISSION4: { image: '4.jpg', descKey: 'transport' },
    MISSION5: { image: '5.jpg', descKey: 'transport' },
    MISSION6: { image: '6.jpg', descKey: 'transport' },
    MISSION7: { image: '7.jpg', descKey: 'observe' },
    MISSION8: { image: '8.jpg', descKey: 'observe' },
    MISSION9: { image: '9.jpg', descKey: 'observe' },
    MISSION10: { image: '10.jpg', descKey: 'hunt' },
    MISSION11: { image: '11.jpg', descKey: 'hunt' },
    MISSION12: { image: '12.jpg', descKey: 'hunt' },
    MISSION13: { image: '13.jpg', descKey: 'transport' },
    MISSION14: { image: '14.jpg', descKey: 'transport' },
    MISSION15: { image: '15.jpg', descKey: 'transport' },
    MISSION16: { image: '16.jpg', descKey: 'transport' },
    MISSION17: { image: '17.jpg', descKey: 'transport' },
    MISSION18: { image: '18.jpg', descKey: 'transport' },
    MISSION19: { image: '19.jpg', descKey: 'transport' },
    MISSION20: { image: '20.jpg', descKey: 'transport' },
    MISSION21: { image: '21.jpg', descKey: 'transport' },
    MISSION22: { image: '22.jpg', descKey: 'disarm' },
    MISSION23: { image: '23.jpg', descKey: 'steal' },
};
