var TileType = {
    VILLAGE: { name: "VILLAGE", image: "village.png" },
    GRASS: { name: "GRASS", image: "grass.png" },
    FOREST: { name: "FOREST", image: "forest.png" },
    CASTLE: { name: "CASTLE", image: "castle.png" },
    TRADER: { name: "TRADER", image: "trader.png" },
    SMITH: { name: "SMITH", image: "smith.png" },
    MUSHROOM: { name: "MUSHROOM", image: "resource1.png" },
    FISH: { name: "FISH", image: "resource2.png" },
    APPLE: { name: "APPLE", image: "resource3.png" },
    DUNGEON1: { name: "DUNGEON", image: "dungeon1.png" },
    DUNGEON2: { name: "DUNGEON", image: "dungeon2.png" },
    DUNGEON3: { name: "DUNGEON", image: "dungeon3.png" },
    DUNGEON4: { name: "DUNGEON", image: "dungeon4.png" },
    DUNGEON5: { name: "DUNGEON", image: "dungeon5.png" },
    DUNGEONFLOOR: { name: "DUNGEONFLOOR", image: "dungeonfloor.png" },
    DUNGEONEXIT1: { name: "DUNGEONEXIT", image: "dungeonexit1.png" },
    DUNGEONEXIT2: { name: "DUNGEONEXIT", image: "dungeonexit2.png" },
    DUNGEONEXIT3: { name: "DUNGEONEXIT", image: "dungeonexit3.png" },
    DUNGEONEXIT4: { name: "DUNGEONEXIT", image: "dungeonexit4.png" },
    DUNGEONEXIT5: { name: "DUNGEONEXIT", image: "dungeonexit5.png" },
    DUNGEONTREASURE: { name: "DUNGEONTREASURE", image: "dungeonfloor.png" },
    DUNGEONTRAP: { name: "DUNGEONTRAP", image: "dungeonfloor.png" },
};
